packages:
  - packages/*
  - packages-devtools/*

catalogs:
  dep:
    commander: ^15.0.0
    rolldown: ^1.2.11
    rolldown-plugin-dts: ^0.28.6
    typescript: ^6.0.3
  dev:
    "@oxc-node/core": ^0.1.3
    "@types/node": ^26.6.3
    oxfmt: ^0.71.0
    oxlint: ^1.86.0
    rolldown: ^1.2.11
    rolldown-plugin-dts: ^0.28.6
    typescript: ^6.0.3
